# Feedback Dashboard Worker
name = "feedback"
main = "worker.js"
compatibility_date = "2026-01-08"
workers_dev = true

# Optional: uncomment to use custom domain
routes = [
  { pattern = "feedback.f1genz.dev", custom_domain = true }
]

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "f1genz-images"
